version: '2.1'
orbs:
  android: circleci/android@3.0.0
jobs:
  build-and-test:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - run:
          name: Set Gradlew Permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Build Project
          command: ./gradlew build
workflows:
  test:
    jobs:
      - build-and-test
