version: '2.1'
orbs:
  android: circleci/android@3.0.0
jobs:
  build-and-test:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-
      - run:
          name: Set Gradlew Permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Build Project
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
workflows:
  test:
    jobs:
      - build-and-test
